 -name: 1st play
  hosts: web1
  tasks: 
    - name: Install the package - httpd, mod_sll, firewalld
      yum: 
        name: 
          - httpd
          - mod_ssl
          - firewalld
        state: latest
    - name: Configure web server 
      copy:
        content: "Welcome To My Server\n"
        dest: /var/www/html/index.html
    - name: Start the service - httpd, firewalld
      service: 
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - httpd
        - firewalld        
    - name: Open the firewall ports with http, https
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: enabled
      loop:
        - http
        - https

