- name: MariaDB server is running
  # yum install mariadb-server
  # systemctl enable --now mariadb
  hosts: database_dev
  vars:
    mariadb_packages:
      - mariadb-server
      - python3-PyMySQL

  tasks:
    - name: MariaDB package are installed
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ mariadb_packages }}"

    - name: Start MariaDB service
      service:
        name: mariadb
        state: started
        enabled: true